TRACE_PATH: '/mnt/sda1/home/caironi/DATA/IS2_PLCchallenge_2025/blind_test_set/traces/'
DATA_PATH: '/mnt/sda1/home/caironi/DATA/IS2_PLCchallenge_2025/blind_test_set/lossy/'
B2B_CKPT_FILE: '/mnt/sda1/home/caironi/IS2_PLC_2025/logs/005/checkpoints/chkpt_gen_BEST.pth'
DEST_PATH: '/mnt/sda1/home/caironi/IS2_PLC_2025/inpainted/005/'
CONTEXT: 4090      # working context size
LP_ORD: 256        # LP order
GAP_SIZE: 512      
WORK_SR: 44100     
XF1: 128           # intra-gap cross-fade extension
XF2: 512           # post gap cross-fade extension
DEVICE: 'cpu'
G_FEATURES: 16
FFT_SIZE: 511
FFT_HOP: 16